export const SET_ALERT = 'SET_ALERT';
export const REMOVE_ALERT = 'REMOVE_ALERT';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';

export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGOUT = 'LOGOUT';

export const CREATE_PALETTE = 'CREATE_PALETTE';
export const FETCH_PALETTES = 'FETCH_PALETTES';
export const FETCH_USER_PALETTES = 'FETCH_USER_PALETTES';
export const FETCH_MY_PALETTES = 'FETCH_MY_PALETTES';

export const FETCH_SINGLE_PALETTE = 'FETCH_SINGLE_PALETTE';
export const CLEAR_SINGLE_PALETTE = 'CLEAR_SINGLE_PALETTE';
